import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MiniKitProvider from "@/src/components/minikit-provider";
import dynamic from "next/dynamic";
import NextAuthProvider from "@/src/components/next-auth-provider";
import { ThirdwebProvider } from "thirdweb/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const ErudaProvider = dynamic(
    () => import("../components/Eruda").then((c) => c.ErudaProvider),
    {
      ssr: false,
    }
  );
  return (
    <ThirdwebProvider>
      <html lang="en">
        <body className={inter.className}>
          <NextAuthProvider>
            <ErudaProvider>
              <MiniKitProvider>{children}</MiniKitProvider>
            </ErudaProvider>
          </NextAuthProvider>
        </body>
      </html>
    </ThirdwebProvider>
  );
}
